### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by ro0NL** [yceruto/twigxray#3]
- [x] only output html comments for html strategic templates (`.html.twig`)
  - from #1 we see the comment is rendered within a <script> block as well (client.js.twig)
- [ ] add feature to opt-out the comment per case
  - currently this will break: https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_3_horizontal_layout.html.twig#L58
   - to opt-out we could support some modifier like `{% html_invisible %}`
- [ ] propose `HtmlDebugNodeVisitor` in twig core
- [ ] propose client integration (see #1) in SF webprofiler bundle
  - completely opt-out profiler related templates from rendering debug comments
- [ ] expose the template path
- [ ] PROFT

cc @yceruto

**Comment by yceruto** [comment]
> only output html comments for html strategic templates (.html.twig)
from #1 we see the comment is rendered within a <script> block as well (client.js.twig)

Should be fixed in https://github.com/yceruto/twigxray/pull/5
